
Vagrant.configure("2") do |config|
	config.vm.define "amaachS" do |control|
	  
		control.vm.box = "bento/ubuntu-16.04"
		control.vm.box_check_update = false
		control.vm.network "private_network", ip: "192.168.56.110", auto_config: true
		control.vm.hostname = "amaachS"
		control.vm.provider "virtualbox" do |v|
			v.memory = "1024"
			v.cpus = 1
			v.name = "amaachS"
		end

		control.vm.provision "shell",
			run: "always",
			inline: "ifconfig eth1 192.168.56.110  netmask 255.255.255.0 up" 
		control.vm.provision "shell",
			run: "always",
			path: "scripts/host.sh",
			privileged: true
	end
end
